/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SendFunds } from './SendFunds'
export * as factories from './factories'
export { SendFunds__factory } from './factories/SendFunds__factory'
